version: "3.8"

services:
  onlineauctionapi:
    image: onlineauctionapi:latest
    container_name: onlineauctionapi
    hostname: auctionapi
    environment:
      - ASPNETCORE_ENVIRONMENT=DEVELOPMENT
      - DB_HOST="mssql,1433"
      - DB_NAME=AuctionDb
      - DB_SA_PASSWORD=Pass123$
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - my_network
    depends_on:
      - mssql
    ports:
      - "5000:80"
      - "5001:443"

  mssql:
    image: mcr.microsoft.com/mssql/server
    hostname: mssql
    environment:
      SA_PASSWORD: "Pass123$"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_server_data:/var/opt/mssql
    networks:
      - my_network

volumes:
  sql_server_data:

networks:
  my_network:
    